config/routes.rb
Cspageedvin::Application.routes.draw do
  root to: 'static_pages#home'

  resources :users do
    member do
      get :listening
      post :updateoffice
    end
  end

  resources :courses do
      get :listeners
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :coursefiles, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/notifications',    to: 'static_pages#notifications'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

 match '/addcourse', to: 'courses#new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def notifications
    if signed_in?
      
      @feed_items = current_user.feed
       @feed2_items = current_user.feed2
    end
  end

  def home
    @profs=User.where(:professor=>true)
    @stud=User.where(:profess=>false, :admin=>false)
  end
  
  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About</h1>
<p>
This page has been designed as part of a project for the course "Project Course"
It is made to be a newer, better version of the current webpage for the Computer Science departement @ IUS
</br>made by <%= mail_to "edsubasic@gmail.com", "edsubasic" %>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
 <%= link_to "Edvin Subasic", "#" %>
</p>

app/views/static_pages/home.html.erb
 <div class="row">
 <div class="center hero-unit">
    <h1>Computer Science and Engineering (CS)</h1>
 
Computer Science is the study of information and algorithms within the context of real and abstract computing devices. Computer scientists are interested in such topics as the representation and storage of information; algorithms to access, display, edit, and transform information; programming languages to express algorithms; and hardware and software processors to execute algorithms. These concerns lead to practical developments in computer systems software, such as operating systems and compilers; in application areas, such as artificial intelligence, computer graphics, and computational biology; and also to theoretical investigations of computers, algorithms, and data.
 
Computer engineering is a closely related field concerned with the design and practical application of computer hardware and software systems to the solution of technological, economic, and societal problems. The computer engineer analyzes a problem and selects from a variety of tools and technologies those most appropriate for its solution. A computer engineer can expect to be involved in hardware design, software creation, and systems integration.
 
After acquiring enough knowledge and experience in computer engineering in the first three years, we motivate our students to engage in industrial training projects. In their fourth year, while taking several elective courses with which they can customize their careers according to their specific interests, they are also expected to propose and realize a graduation project.
 
<h3>The graduate of the computer engineering department will gain the following skills:</h3>
 <ul>
<li>Capability to design and analyze application software in terms of both hardware and software aspects and requirements.</li>
<li>Capability to use their computer engineering and problem solving skills in real life situations/applications.</li>
<li>Capability to acquire knowledge to follow up the developments in Computer Sciences and computer engineering.</li>
<li>Excellent verbal and communication skills.</li>
</ul>
    </br><%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

<div  style="width:45%; margin-left:auto; margin-right:auto;padding: 2px 14px;">
  <%= link_to image_tag("ius.jpg", alt: "IUS", class:"pull-left"), 'http://ius.edu.ba/' %>
  <%= link_to image_tag("logo.png", alt: "IUS-CS", class:"pull-right"), 'http://www.ius.edu.ba/Default.aspx?PageContentID=77&tabid=99' %>
</div>
</div>

app/views/static_pages/notifications.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
       
      </section>
    </aside>
    <div class="span4 pull-left">
      <h3>Notification Feed</h3>
      <%= render 'shared/feed' %>
    </div>

    <div class="span4 pull-right">
      <h3>Resources Feed</h3>
      <%= render 'shared/feed2' %>
    </div>

  </div>

<% else %>
<div class="center hero-unit">
  <h1>You are not signed in!</h1>
  <%= link_to "Sign in now!", signin_path, class: "btn btn-large btn-primary" %><%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-warning" %>
</div>
<% end %>