config/routes.rb
Cspageedvin::Application.routes.draw do
  root to: 'static_pages#home'

  resources :users do
    member do
      get :listening
      post :updateoffice
    end
  end

  resources :courses do
      get :listeners
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :coursefiles, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/notifications',    to: 'static_pages#notifications'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

 match '/addcourse', to: 'courses#new'

end

app/views/shared/_coursefiles_form.html.erb
<%= form_for(@coursefile, :html => { :multipart => true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :course_id %>
  <%= f.label :name %>
    <%= f.text_field :name %>
  <div class="field">
    <%= f.text_area :description, placeholder: "Add description" , class:"input-xsmall"%>
  </div>
  <%= f.file_field :file %>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="notifications">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed2.html.erb
<% if @feed2_items.any? %>
  <ol class="notifications">
    <%= render partial: 'shared/feed2_item', collection: @feed2_items %>
  </ol>
<% end %>

app/views/shared/_feed2_item.html.erb
<li>
  <span class="content"> <%= link_to feed2_item.name+" (Download)", feed2_item.file.url(false) %> for  <%= link_to feed2_item.course.name, feed2_item.course %></br><%=feed2_item.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed2_item.created_at) %> ago.
 
  <% if current_user?(feed2_item.course.user) %>
    <%= link_to "delete", feed2_item, method: :delete,
                                     data: { confirm: 'You sure?' },
                                     title: feed2_item.name %>
  <% end %>
</span>
</li>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <span class="user">
    <%= link_to feed_item.course.name, feed_item.course %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.course.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_notification_form.html.erb
<%= form_for(@notification) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :course_id %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Post notification" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= listening_user_path(@user) %>">
    <strong id="listening" class="stat">
     Courses taking: <%= @user.listened_courses.count %> 
    </strong>
    
  </a>
  
</div>

app/views/shared/_statscourse.html.erb

<div class="stats">
 <a href="<%= course_listeners_path(@course) %>">
			<strong id="listeners" class="stat">
				Students taking: <%= @course.listeners.count %> 
			</strong>
			
		</a>
  
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
		<% if(current_user.avatar?) %>
		<%= image_tag current_user.avatar.url(), class:"avatar" %>
		<% else %>
		<%= image_tag ("user_default.png"), class:"avatar" %>
		<% end %>
	</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>