config/routes.rb
Cspageedvin::Application.routes.draw do
  root to: 'static_pages#home'

  resources :users do
    member do
      get :listening
      post :updateoffice
    end
  end

  resources :courses do
      get :listeners
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :coursefiles, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/notifications',    to: 'static_pages#notifications'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

 match '/addcourse', to: 'courses#new'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/home">CS @ IUS</a>
    by  Edvin Subasic
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar  navbar-inverse navbar-top">
  <div class="navbar-inner">
    <div class="container">

     
      <%= link_to "CS-IUS", root_path, id: "headerlogo" %>

      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>

            <li id="fat-menu" class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Professors <b class="caret"></b>
              </a>
           <ul class="dropdown-menu">
              <% profs=User.where(:professor=>true) %>
              <% profs.each do |prof| %>
              <li><%= link_to prof.name, prof %></li>
              <%end%>
           </ul>
         </li>

          <li id="fat-menu" class="dropdown">
           

           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Courses <b class="caret"></b>
              </a>
           <ul class="dropdown-menu">
             <% courses = current_user.listened_courses %>
              <% courses.each do |course| %>
              <li><%= link_to course.name, course %></li>
              <%end%>
            <li class="divider"></li>
              <% courses=Course.all %>
              <% courses.each do |course| %>
              <li><%= link_to course.name, course %></li>
              <%end%>
           </ul>
         </li>

          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <%end%>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                 <% if current_user.professor? %>
                 <li><%= link_to "Add Course", '/addcourse' %></li>
                 <%end%>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Feed", '/notifications' %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>

               <li id="fat-menu" class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Courses <b class="caret"></b>
              </a>
           <ul class="dropdown-menu">
              <% courses=Course.all %>
              <% courses.each do |course| %>
              <li><%= link_to course.name, course %></li>
              <%end%>
           </ul>
         </li>

           <li id="fat-menu" class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Professors <b class="caret"></b>
              </a>
           <ul class="dropdown-menu">
              <% profs=User.where(:professor=>true) %>
              <% profs.each do |prof| %>
              <li><%= link_to prof.name, prof %></li>
              <%end%>
           </ul>
         </li>


            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>